### ISSUE TITLE
I can't retrieve post id inside the plugin

### ISSUE THREAD

**Issue by tyl3r** [bradt/live-comment-preview#3]
Hi bradt,

I'm trying to output different layout depending on the post type, i'm doing the IF on comment-preview.php like this:

``` php
<?php 
global $post;
$post_id = $post->ID;

$post_type = get_post_type( $post_id );

if ( $post_type == 'xxx' ) { ?>

<div class="modul-contingut">
    <p>
    <strong><?php echo COMMENT_TITLE; ?></strong><br>
    <?php echo COMMENT_CONTENT; ?><br>
    Nota: <strong><span class="color-groc"><?php echo COMMENT_RATING; ?></span>/10</strong>
    </p>
</div>

<?php } elseif ( $post_type == 'yyy' ) { ?>

<div class="modul-contingut">
    <p>
    <?php echo COMMENT_CONTENT; ?>
    </p>
</div>

<?php } ?>
```

I don't know why, but this always retrieve the ID of the first post on the blog :neckbeard: 

I also tried to do the the IF in the 3 method $previewFormat but WP globals don't work inside the plugin.

Do you have any idea for solve this issue?

Regards.

P.D: COMMENT_TITLE and COMMENT_RATING are 2 added extra fields on my comment system.

**Comment by bradt** [comment]
Sounds like a sidebar widget or some other code executed before the comments is using the `$post` variable but not setting it back to the queried post. You should use [`get_queried_object()`](http://codex.wordpress.org/Function_Reference/get_queried_object) though anyways.
